apiVersion: v1
kind: ReplicationController
metadata:
  name: auth-microservice
spec:
  replicas: 1
  selector:
    app: auth-microservice
  template:
    metadata:
      name: auth-microservice
      labels:
        app: auth-microservice
    spec:
      containers:
      - image: 172.18.51.9:5000/authmicroservice
        ports:
        - containerPort: 8080
        name: auth-microservice
