apiVersion: v1
kind: ReplicationController
metadata:
  name: cart-microservice
spec:
  replicas: 1
  selector:
    app: cart-microservice
  template:
    metadata:
      name: cart-microservice
      labels:
        app: cart-microservice
    spec:
      containers:
      - image: 172.18.51.9:5000/cartmicroservice
        ports:
        - containerPort: 8080
        name: cart-microservice
