apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-service
spec:
  selector:
    database: mysql
  replicas: 1
  template:
    metadata:
      labels:
        database: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        volumeMounts:
        - name: mysqldata
          mountPath: "/data"
      volumes:
      - name: mysqldata
        emptyDir: {}

