apiVersion: v1
kind: ReplicationController
metadata:
  name: order-microservice
spec:
  replicas: 1
  selector:
    app: order-microservice
  template:
    metadata:
      name: order-microservice
      labels:
        app: order-microservice
    spec:
      containers:
      - image: 172.18.51.9:5000/ordermicroservice
        ports:
        - containerPort: 8080
        name: order-microservice
