apiVersion: v1
kind: ReplicationController
metadata:
  name: picture-microservice
spec:
  replicas: 1
  selector:
    app: picture-microservice
  template:
    metadata:
      name: picture-microservice
      labels:
        app: picture-microservice
    spec:
      containers:
      - image: 172.18.51.9:5000/picturemicroservice
        ports:
        - containerPort: 8080
        name: picture-microservice
