apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-cache-service
spec:
  replicas: 1
  selector:
    app: redis-cache-service
  template:
    metadata:
      labels:
        app: redis-cache-service
    spec:
      containers:
      - image: redis
        ports:
        - containerPort: 6379 
        name: redis-cache-service
