apiVersion: v1
kind: ReplicationController
metadata:
  name: userdetail-microservice
spec:
  replicas: 1
  selector:
    app: userdetail-microservice
  template:
    metadata:
      name: userdetail-microservice
      labels:
        app: userdetail-microservice
    spec:
      containers:
      - image: 172.18.51.9:5000/userdetailmicroservice
        ports:
        - containerPort: 8080
        name: userdetail-microservice
